# Generated by Django 5.2.5 on 2025-08-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='choice',
            name='unique question and order',
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique question and order'),
        ),
    ]
