# Generated by Django 5.2.5 on 2025-09-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_answer_unique_answer_and_question_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_answer_question', 'Can answer question')]},
        ),
    ]
